name: simple-web-app

on:
  workflow_dispatch:

jobs:
  Build:

    runs-on: ubuntu-latest
    
    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~

      - name: Check out Code
        uses: actions/checkout@v3

      - name: echoing the file name
        run: echo $GITHUB_WORKFLOW:$GITHUB_RUN_ID

# ~~~~~~~~~~~~~~~~~~~ Building Container Image ~~~~~~~~~~~~~~~~~~~
        
      - name: Building Docker Images
        run: |
          docker image build -t $GITHUB_WORKFLOW:$GITHUB_RUN_ID . 
          docker image tag $GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:$GITHUB_RUN_ID
          docker image tag $GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:latest

# ~~~~~~~~~~~~~~~~~~~ Pushing Container Image ~~~~~~~~~~~~~~~~~~~

      - name: Pushing Image onto Docker Hub
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          docker images
          docker image push nbharathkumara/$GITHUB_WORKFLOW:$GITHUB_RUN_ID
          docker image push nbharathkumara/$GITHUB_WORKFLOW:latest
          docker image rmi $GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:latest

  Deploy:      
  
    needs: [Build]
    
    runs-on: ubuntu-latest
    
    steps:

# ~~~~~~~~~~~~~~~~~~~ Configuring Deploying Environment ~~~~~~~~~~~~~~~~~~~

      - name: Deploying the Docker
        env: 
          PRIVATE_KEY: ${{secrets.SSH_KEY}}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.SSH_USER}}

# ~~~~~~~~~~~~~~~~~~~ Deploying Container Image ~~~~~~~~~~~~~~~~~~~
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            sudo docker container rm -f bkob-server
            sudo docker system prune -a -f
            sudo docker run -p 80:80 -d --name bkob-server nbharathkumara/simple-web-app:latest
            '
